apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ip-rule-operator
  name: ip-rule-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ip-rule-manager-role
subjects:
- kind: ServiceAccount
  name: ip-rule-controller-manager
  namespace: ip-rule-operator
