apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-role
  labels:
    app.kubernetes.io/name: ip-rule-operator
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups:
    - api.operator.brtrm.dev
  resources:
    - agents
    - ipruleconfigs
    - iprules
  verbs:
    - '*'
- apiGroups:
    - apps/v1
  resources:
    - daemonsets/finalizers
  verbs:
    - update
