apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent-binding
  labels:
    app.kubernetes.io/name: ip-rule-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agent-role
subjects:
- kind: ServiceAccount
  name: agent
  namespace: system
