# This rule is not used by the project ip-rule-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the brtrm.dev.brtrm.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ip-rule-operator
    app.kubernetes.io/managed-by: kustomize
  name: iprule-editor-role
rules:
- apiGroups:
  - brtrm.dev.brtrm.dev
  resources:
  - iprules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - brtrm.dev.brtrm.dev
  resources:
  - iprules/status
  verbs:
  - get
