apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: ip-rule-operator
    app.kubernetes.io/managed-by: kustomize
  name: ip-rule-controller-manager
  namespace: ip-rule
