apiVersion: brtrm.dev.brtrm.dev/v1alpha1
kind: IpRule
metadata:
  labels:
    app.kubernetes.io/name: ip-rule-operator
    app.kubernetes.io/managed-by: kustomize
  name: iprule-sample
spec:
  # TODO(user): Add fields here
